config/routes.rb
ResourceForkRepo::Application.routes.draw do
  root 'resource_forks#index'
  resources :resource_forks
  resources :resource_types
  resources :resources
  resources :transforms

end

app/controllers/transforms_controller.rb
class TransformsController < ApplicationController
  before_action :set_transform, only: [:show, :edit, :update, :destroy]

  # GET /transforms
  # GET /transforms.json
  def index
    @transforms = Transform.all
  end

  # GET /transforms/1
  # GET /transforms/1.json
  def show
  end

  # GET /transforms/new
  def new
    @transform = Transform.new
  end

  # GET /transforms/1/edit
  def edit
  end

  # POST /transforms
  # POST /transforms.json
  def create
    @transform = Transform.new(transform_params)

    respond_to do |format|
      if @transform.save
        format.html { redirect_to @transform, notice: 'Transform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transform }
      else
        format.html { render action: 'new' }
        format.json { render json: @transform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transforms/1
  # PATCH/PUT /transforms/1.json
  def update
    respond_to do |format|
      if @transform.update(transform_params)
        format.html { redirect_to @transform, notice: 'Transform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transforms/1
  # DELETE /transforms/1.json
  def destroy
    @transform.destroy
    respond_to do |format|
      format.html { redirect_to transforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transform
      @transform = Transform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transform_params
      params.require(:transform).permit(:data, :content_type, :resource_id)
    end
end

app/helpers/transforms_helper.rb
module TransformsHelper
end

app/views/transforms/_form.html.erb
<%= form_for(@transform) do |f| %>
  <% if @transform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transform.errors.count, "error") %> prohibited this transform from being saved:</h2>

      <ul>
      <% @transform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :resource_id %><br>
    <%= f.text_field :resource_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transforms/edit.html.erb
<h1>Editing transform</h1>

<%= render 'form' %>

<%= link_to 'Show', @transform %> |
<%= link_to 'Back', transforms_path %>

app/views/transforms/index.html.erb
<h1>Listing transforms</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Content type</th>
      <th>Resource</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transforms.each do |transform| %>
      <tr>
        <td><%= transform.data %></td>
        <td><%= transform.content_type %></td>
        <td><%= transform.resource %></td>
        <td><%= link_to 'Show', transform %></td>
        <td><%= link_to 'Edit', edit_transform_path(transform) %></td>
        <td><%= link_to 'Destroy', transform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transform', new_transform_path %>

app/views/transforms/new.html.erb
<h1>New transform</h1>

<%= render 'form' %>

<%= link_to 'Back', transforms_path %>

app/views/transforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @transform.data %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @transform.content_type %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @transform.resource %>
</p>

<%= link_to 'Edit', edit_transform_path(@transform) %> |
<%= link_to 'Back', transforms_path %>