config/routes.rb
ResourceForkRepo::Application.routes.draw do
  root 'resource_forks#index'
  resources :resource_forks
  resources :resource_types
  resources :resources
  resources :transforms

end

app/models/resource_fork.rb
class ResourceFork < ActiveRecord::Base
	has_many :resource_types, dependent: :destroy
	has_many :resources, through: :resource_types
  accepts_nested_attributes_for :resource_types
end

app/controllers/resource_forks_controller.rb
class ResourceForksController < ApplicationController
  before_action :set_resource_fork, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /resource_forks
  # GET /resource_forks.json
  def index
    @resource_forks = ResourceFork.all
  end

  # GET /resource_forks/1
  # GET /resource_forks/1.json
  def show
  end

  # GET /resource_forks/new
  def new
    @resource_fork = ResourceFork.new
  end

  # GET /resource_forks/1/edit
  def edit
  end

  # POST /resource_forks
  # POST /resource_forks.json
  def create
    @resource_fork = ResourceFork.new(resource_fork_params)

    respond_to do |format|
      if @resource_fork.save
        format.html { redirect_to @resource_fork, notice: 'ResourceFork was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resource_fork }
      else
        format.html { render action: 'new' }
        format.json { render json: @resource_fork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_forks/1
  # PATCH/PUT /resource_forks/1.json
  def update
    respond_to do |format|
      if @resource_fork.update(resource_fork_params)
        format.html { redirect_to @resource_fork, notice: 'ResourceFork was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource_fork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_forks/1
  # DELETE /resource_forks/1.json
  def destroy
    @resource_fork.destroy
    respond_to do |format|
      format.html { redirect_to resource_forks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_fork
      @resource_fork = ResourceFork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_fork_params
      params.require(:resource_fork).permit!
    end
end

app/helpers/resource_fork_helper.rb
module ResourceForkHelper
end

app/views/resource_forks/index.html.haml
%table.resource_forks{border: 1}
  %caption
    %h1
      = link_to "Resource Forks", resource_forks_path
      = @resource_forks.count
  %thead
    %tr
      %th Count
      %th File Name
      %th Type
      %th Creator
  %tbody
    - @resource_forks.each do |resource_fork|
      %tr.resource_fork
        %td.id
          = resource_fork.resource_types.count
        %td.name
          = link_to Base64.decode64(resource_fork.file_name), resource_fork_path(resource_fork)
        %td.type
          = Base64.decode64(resource_fork.mac_type)
        %td.creator
          = Base64.decode64(resource_fork.mac_creator)

app/views/resource_forks/index.text.haml
- @resource_forks.each do |resource_fork|
  = "#{resource_fork.file_name},#{resource_fork.mac_creator},#{resource_fork.mac_type},#{resource_fork_url(resource_fork, :text)}"

app/views/resource_forks/new.html.haml
= form_for @resource_fork do |upload_form|
  = upload_form.file_field 'resource_fork'
  = upload_form.submit 'Upload'

app/views/resource_forks/show.html.haml
.resource_forks_link
  = link_to 'Resource Forks', resource_forks_path
.resource_fork
  = link_to Base64.decode64(@resource_fork.file_name), resource_fork_path(@resource_fork)
%table.resource{border: 1}
  %caption
    %h1
      = link_to Base64.decode64(@resource_fork.file_name), resource_fork_path(@resource_fork)
  %thead
    %tr
      %th{width: '15%'} Count
      %th Resource Type
  %tbody
    - @resource_fork.resource_types.each do |resource_type|
      %tr.resource
        %td.id
          = resource_type.resources.count
        %td.name
          = link_to Base64.decode64(resource_type.name), resource_type_path(resource_type)

app/views/resource_forks/show.text.haml
- resource_type_ids = @resource_fork.resource_types.map! {|type| resource_type_url(type, :text)}.join(';')
= "#{@resource_fork.file_name},#{@resource_fork.mac_creator},#{@resource_fork.mac_type},#{resource_type_ids}"